#!/bin/bash
# Wrapper for launching kubelet via docker.
#
# Make sure to set KUBELET_IMAGE_TAG to an image tag published here:
# https://quay.io/repository/coreos/hyperkube?tab=tags Alternatively,
# override KUBELET_IMAGE to a custom image.

set -e

function require_ev_all() {
	for rev in $@ ; do
		if [[ -z "${!rev}" ]]; then
			echo "${rev}" is not set
			exit 1
		fi
	done
}

function require_ev_one() {
	for rev in $@ ; do
		if [[ ! -z "${!rev}" ]]; then
			return
		fi
	done
	echo One of $@ must be set
	exit 1
}

if [[ -n "${KUBELET_VERSION}" ]]; then
	echo KUBELET_VERSION environment variable is deprecated, please use KUBELET_IMAGE_TAG instead
fi

if [[ -n "${KUBELET_IMAGE}" ]]; then
	echo KUBELET_IMAGE environment variable is deprecated, please use the KUBELET_IMAGE_URL instead
fi

if [[ -n "${DOCKER_OPTS}" ]]; then
	echo DOCKER_OPTS environment variable is deprecated, please use the DOCKER_RUN_ARGS instead
fi

KUBELET_IMAGE_TAG="${KUBELET_IMAGE_TAG:-${KUBELET_VERSION}}"

require_ev_one KUBELET_IMAGE KUBELET_IMAGE_TAG

KUBELET_IMAGE_URL="${KUBELET_IMAGE_URL:-${KUBELET_IMAGE:-gcr.io/google-containers/hyperkube}}"
KUBELET_IMAGE="${KUBELET_IMAGE:-${KUBELET_IMAGE_URL}:${KUBELET_IMAGE_TAG}}"

DOCKER_RUN_ARGS="${DOCKER_RUN_ARGS:---cap-add SYS_ADMIN --security-opt label:disable}"
DOCKER_RUN_ARGS="${DOCKER_RUN_ARGS} ${DOCKER_OPTS}"

mkdir --parents /etc/kubernetes
mkdir --parents /var/lib/docker
mkdir --parents /var/lib/kubelet
mkdir --parents /run/kubelet

DOCKER="${DOCKER:-/usr/bin/docker}"
KUBELET_IMAGE_ARGS=${KUBELET_IMAGE_ARGS:-/kubelet}
set -x
exec ${DOCKER} ${DOCKER_GLOBAL_ARGS} \
	run ${DOCKER_RUN_ARGS} \
	--mount type=bind,bind-propagation=rprivate,source=/etc/kubernetes,target=/etc/kubernetes \
	--mount type=bind,bind-propagation=rprivate,source=/etc/ssl/certs,target=/etc/ssl/certs,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/usr/share/ca-certificates,target=/usr/share/ca-certificates,readonly\
	--mount type=bind,bind-propagation=rslave,source=/var/lib/docker,target=/var/lib/docker \
	--mount type=bind,bind-propagation=shared,source=/var/lib/kubelet,target=/var/lib/kubelet \
	--mount type=bind,bind-propagation=rprivate,source=/var/log,target=/var/log \
	--mount type=bind,bind-propagation=rprivate,source=/usr/lib/os-release,target=/usr/lib/os-release,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/run,target=/run \
	--mount type=bind,bind-propagation=rprivate,source=/sys,target=/sys \
	--mount type=bind,bind-propagation=rprivate,source=/lib/modules,target=/lib/modules,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/etc/machine-id,target=/etc/machine-id,readonly \
	${KUBELET_IMAGE} \
		${KUBELET_IMAGE_ARGS} \
		-- "$@"
